config/routes.rb
Rails.application.routes.draw do
  get 'admin' => 'admin#index'

  controller :session do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

  resources :users
  #resources :orders
  #resources :line_items
  #resources :carts

  resources :products do
    get :who_bought, on: :member # Try it out: `curl --silent http://localhost:3000/products/3/who_bought.atom`
  end

  scope '(:locale)' do
    resources :orders
    resources :line_items
    resources :carts
    root 'store#index', as: 'store_index', via: :all
    #root 'store#index', as: 'store_index' # Using `as:` allows the existing tests to continue working. Rails creates `store_index_path` & `store_index_url` accessor methods.
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Book Depot</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class='<%= controller.controller_name %>'>
    <div id="banner">
      <%= form_tag store_index_path, class: 'locale' do %>
        <%= select_tag 'set_locale', options_for_select(LANGUAGES, I18n.locale.to_s), onchange: 'this.form.submit()'%>
        <%= submit_tag 'submit' %>
        <%= javascript_tag "$('.locale input').hide()" %>
      <% end %>
      <%= image_tag 'logo.svg', alt: 'The Awesome Bookshelf' %>
      <span class="title"><%= @page_title %></span>
    </div>
    <div id="columns">
      <div id="side">
        <% if @cart %><!--If @cart is set for any controller then show the cart in the sidebar. Without this, tests would fail & we would get errors visiting another page where @cart is not set in its controller.-->
          <%= hidden_div_if(@cart.line_items.empty?, id: 'cart') do %><!--Use hidden_div_if() helper method, div will have an id of cart if the condition is not met-->
            <%= render @cart %><!--We're invoking the store layout while looking at the index action.-->
          <% end %>
        <% end %>
        <ul>
          <!--Text to be translated are done with calls to I18n.translate - aliased to I18n.t or the 't' helper method-->
          <li><%= link_to t('.home'), store_index_path(locale: I18n.locale) %></li>
          <li><a href="#"><%= t('.questions') %></a></li>
          <li><a href="#"><%= t('.news')%></a></li>
          <li><a href="#"><%= t ('.contact')%></a></li>
        </ul>

        <% if session[:user_id] %>
          <ul>
            <li><%= link_to 'Orders', orders_path %></li>
            <li><%= link_to 'Products', products_path %></li>
            <li><%= link_to 'Users', users_path %></li>
          </ul>
          <%= button_to 'Logout', logout_path, method: :delete %>
        <% end %>
      </div>
      <div id="main">
        <%= yield %>
      </div>
    </div>
  </body>
</html>